### ISSUE TITLE
VPNUNLIMTED missing from list of VPN Providers

### ISSUE THREAD

**Issue by tonyhamm** [clowrym/docker-templates#6]
VPNUNLIMTED missing from list of VPN Providers.  The openvpn client installed supports VPNUNLIMITED but it is not a choice from the dropdown in UnRaid

**Comment by swbradshaw** [comment]
PRIVADO was also removed on Nov 24.  @clowrym Any ETA to when this will be corrected?

**Comment by clowrym** [comment]
Added both
